import {
  FaPlus,
  FaPencilAlt,
  FaTrash,
  FaEye,
  FaHorseHead,
  FaCalendarAlt,
  FaClone,
  FaCheck,
  FaTimes,
  FaExclamationTriangle,
  FaArrowUp,
  FaUser,
  FaPhone,
  FaEnvelope,
  FaCalendar,
  FaList,
  FaLink,
  FaChevronDown,
  FaUsers,
  FaInfoCircle,
  FaSave,
  FaBan,
  FaSpinner,
  FaGraduationCap,
  FaShoppingBasket,
  FaUserGraduate,
} from 'react-icons/fa';

export const Icons = {
  Add: FaPlus,
  Edit: FaPencilAlt,
  Delete: FaTrash,
  View: FaEye,
  Horse: FaHorseHead,
  Calendar: FaCalendarAlt,
  Template: FaClone,
  Check: FaCheck,
  Close: FaTimes,
  Warning: FaExclamationTriangle,
  Remove: FaArrowUp,
  User: FaUser,
  Users: FaUsers,
  Phone: FaPhone,
  Email: FaEnvelope,
  Date: FaCalendar,
  List: FaList,
  Link: FaLink,
  ChevronDown: FaChevronDown,
  Info: FaInfoCircle,
  Save: FaSave,
  Cancel: FaBan,
  Loading: FaSpinner,
  Lesson: FaGraduationCap,
  Packages: FaShoppingBasket,
  PrivateLesson: FaUserGraduate,
  GroupLesson: FaUsers,
  Service: FaShoppingBasket,
};

export const renderIcon = (Icon, props = {}) => {
  return <Icon {...props} />;
};

export default Icons;
